version: '3.8'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  web_app:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - DEBUG=True