name: CD Pipeline

on:
  push:
    branches:
      - actions/workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up SSH Key
      shell: bash
      run: |
        echo "${{ secrets.EC2_KEY }}" > ~/neural-city-backend.pem
        chmod 400 ~/neural-city-backend.pem

    - name: Deploy Code
      shell: bash
      run: |
        # Copy all project files to the EC2 instance
        scp -o StrictHostKeyChecking=no -i ~/neural-city-backend.pem -r ./server/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/op-hastinapur-deployo/
        
        # SSH into the EC2 instance and deploy
        ssh -o StrictHostKeyChecking=no -i ~/neural-city-backend.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
          cd /home/${{ secrets.EC2_USER }}/op-hastinapur-deploy &&
          docker-compose up --build -d
        "
